---
- name: system configuration for MASTERS
  hosts: masters
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    #firewalld
    - name: firewalld rules
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        zone: public
        state: enabled
      with_items:
        - { port: "6443", proto: "tcp" }
        - { port: "2379-2380", proto: "tcp" }
        - { port: "10250", proto: "tcp" }
        - { port: "10251", proto: "tcp" }
        - { port: "10252", proto: "tcp" }
        - { port: "10255", proto: "tcp" }
        - { port: "30000-32767", proto: "tcp" }
        - { port: "16443", proto: "tcp" }

    - name: reload
      service:
        name: firewalld
        state: reloaded
    #>>copyfile
    - name: ">>"
      shell: |
        firewall-cmd --list-all --zone=public >> /tmp/rules.txt
